src/WebUI/Controllers/InstitutionController.cs
using BLL.Common.Interfaces;
using BLL.Common.Repository;
using BLL.DTO.InstitutionDTOs;
using BLL.TableParameters;
using BLL.UserDTOs;
using BLL.Validator;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class InstitutionController : BaseController
    {

        private readonly IInstitutionRepository _institutionRepository;

        private readonly IValidator<CreateInstitutionDto> _CreateInstitutionDtoValidator;
        private readonly IValidator<UpdateInstitutionDto> _UpdateInstitutionDtoValidator;
        public InstitutionController(IInstitutionRepository institutionRepository, 
            IValidator<CreateInstitutionDto> createInstitutionDtoValidator,
            IValidator<UpdateInstitutionDto> updateInstitutionDtoValidator)
        {
            _institutionRepository = institutionRepository;
            _CreateInstitutionDtoValidator = createInstitutionDtoValidator;
            _UpdateInstitutionDtoValidator = updateInstitutionDtoValidator;
        }


        [HttpPost]
        public async Task<ActionResult> LoadInstitutionDatatable(DataTablesParameters parameters)
        {
            try
            {
                var result = await _institutionRepository.GetAllInstitutions(parameters);
                return Json(new
                {
                    draw = parameters.Draw,
                    recordsFiltered = parameters.TotalCount,
                    recordsTotal = parameters.TotalCount,
                    data = result
                });

            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }
        }


        [HttpPost]
        public async Task<JsonResult> GetInstitutions(int? InstitutionId)
        {
            var institutions = await _institutionRepository.GetInstitutions();
            var selectListinstitutionsVm = institutions.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name,
                Selected = x.Id == InstitutionId
            });
            ViewBag.Institutions = selectListinstitutionsVm;
            return Json(selectListinstitutionsVm);



        }

        [HttpGet]
        public async Task<ActionResult> GetDetails(int id)
        {
            try
            {

                var user = await _institutionRepository.GetInstitution(id);

                return PartialView("~/Views/Institution/Details.cshtml", user);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }


        [HttpGet]
        public ActionResult GetCreate() => PartialView("~/Views/Institution/Create.cshtml");

        [HttpPost]
        public async Task<ActionResult> Create(CreateInstitutionDto createInstitution)
        {
            try
            {
                var validationResult = _CreateInstitutionDtoValidator.Validate(createInstitution);
                if (!validationResult.IsValid)
                {
                    foreach (var failure in validationResult.Errors)
                    {
                        ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                    }

                    TempData["ErrorInstitution"] = "ErrorInstitution";
                    return PartialView("~/Views/Institution/Create.cshtml", createInstitution);
                }

                var result = await _institutionRepository.Add(createInstitution);
                if (result)
                {
                    return Json(new { success = true });
                }
                else
                {
                    TempData["ErrorInstitution"] = "ErrorInstitution";
                    return PartialView("~/Views/Institution/Create.cshtml", createInstitution);
                }

            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }


        [HttpGet]
        public async Task<ActionResult> GetEdit(int id)
        {
            try
            {

                var institution = await _institutionRepository.GetInstitutionForUpdate(id);
                return PartialView("~/Views/Institution/Edit.cshtml", institution);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }
        [HttpPost]
        public async Task<ActionResult> Edit(int institutionId, UpdateInstitutionDto updateInstitutionDto)
        {
            var validationResult = _UpdateInstitutionDtoValidator.Validate(updateInstitutionDto);
            if (!validationResult.IsValid)
            {
                foreach (var failure in validationResult.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }

                TempData["ErrorInstitution"] = "ErrorInstitution";
                return PartialView("~/Views/Institution/Edit.cshtml", await _institutionRepository.GetInstitutionForUpdate(institutionId));
            }
            updateInstitutionDto.Id = institutionId;
            var result = await _institutionRepository.Update(updateInstitutionDto);
            if (result)
            {
                return Json(new { success = true });
            }
            else
            {
                TempData["ErrorInstitution"] = "ErrorInstitution";
                return PartialView("~/Views/Institution/Edit.cshtml", await _institutionRepository.GetInstitutionForUpdate(institutionId));
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetDelete(int id)
        {
            try
            {

                //var institution = await _institutionRepository.GetInstitution(id);

                return PartialView("~/Views/Institution/Delete.cshtml", id);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }


        [HttpPost]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var success = await _institutionRepository.Delete(id);
                if (success)
                {
                    return Json(new { success = true });
                }
                else
                {
                    return Json(new { success = false });
                }
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }


    }
}

src/WebUI/Views/Institution/Create.cshtml
@model BLL.DTO.InstitutionDTOs.CreateInstitutionDto

@if (TempData["ErrorInstitution"] != null)
{
    <div class="alert alert-danger">
        <strong>Sorry!</strong> - @TempData["ErrorInstitution"]
    </div>
}

@using (Html.BeginForm("Create", "Institution", FormMethod.Post, new { id = "createInstitutionForm", @class = "needs-validation", novalidate = "novalidate" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="mb-3 row">
            @Html.LabelFor(model => model.InstCode, "*Code", new { @class = "col-sm-3 form-label" })
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.InstCode, new { @class = "form-control", placeholder = "ACXXX", maxlength = "5", @style = "max-width: 100% !important; width: 100%;" })
                @Html.ValidationMessageFor(model => model.InstCode, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.Name, "*Name", new { @class = "col-sm-3 form-label" })
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Banca of code ACXXX", maxlength = "255", @style = "max-width: 100% !important; width: 100%;" })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-sm-3 form-label" for="AdditionalInfo">Additional Info</label>
            <div class="col-sm-9">
                <textarea id="AdditionalInfo" rows="5" name="AdditionalInfo" maxlength="1000" style="max-width: 100% !important; width: 100%;" class="form-control" placeholder="Big Message"></textarea>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-success" style="width: 100px;" onclick="handleSubmitButton('#createInstitutionForm', 'InstitutionDatatable')">Save</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
}

src/WebUI/Views/Institution/Delete.cshtml
@model int
<div>
    <div class="modal-body">
        <div class="col-sm-12">
            <div class="alert alert-danger alert-dismissible fade show mt-1 px-1 mb-0 text-center" role="alert">
                <i class="uil uil-exclamation-octagon d-block display-4 mt-2 mb-3 text-danger"></i>
                <h1 class="text-danger">Delete</h1>
                <h3>
                    Are you sure?
                </h3>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" id="deleteCurrent" onclick="deleteCurrentInstitution(@Model)" class="btn btn-danger waves-effect waves-light" data-bs-dismiss="modal">Delete</button>

        <button type="button" class="btn btn-light waves-secondary" data-bs-dismiss="modal">Cancel</button>

    </div>
</div>

src/WebUI/Views/Institution/Details.cshtml
@model BLL.DTO.InstitutionDTOs.InstitutionDto

<div class="modal-body">
    <div class="col-sm-12">
        <h2>Details</h2>
        <div class="mb-3 row">
            <div class="col-md-6">
                @Html.LabelFor(model => model.InstCode)
                @Html.TextBoxFor(model => model.InstCode, new { @class = "form-control", @disabled = true, @style = "max-width: 100% !important; width: 100%;" })
            </div>
            <div class="col-md-6">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @disabled = true, @style = "max-width: 100% !important; width: 100%;" })

            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-md-12">
                <label for="AdditionalInfo" class="col-md-4 col-form-label">Additional Info</label>
                <textarea id="AdditionalInfo" rows="3" class="form-control" style="resize: none; max-width: 100% !important; width: 100%;" disabled>@Model.AdditionalInfo</textarea>
            </div>
        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
</div>

src/WebUI/Views/Institution/Edit.cshtml
@model BLL.DTO.InstitutionDTOs.UpdateInstitutionDto

@if (TempData["ErrorInstitution"] != null)
{
    <div class="alert alert-danger">
        <strong>Sorry!</strong> - @TempData["ErrorInstitution"]
    </div>
}

@using (Html.BeginForm("Edit", "Institution", new { institutionId = Model.Id }, FormMethod.Post, new { id = "updateInstitutionForm", @class = "needs-validation", novalidate = "novalidate" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="mb-3 row">
            @Html.LabelFor(model => model.InstCode, "*Code", new { @class = "col-sm-3 form-label" })
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.InstCode, new { @class = "form-control", placeholder = "ACXXX", maxlength = "5", @disabled = "disabled", @style = "max-width: 100% !important; width: 100%;" })
                @Html.ValidationMessageFor(model => model.InstCode, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.Name, "*Name", new { @class = "col-sm-3 form-label" })
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Banca of code ACXXX", maxlength = "255", @style = "max-width: 100% !important; width: 100%;" })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-sm-3 form-label" for="AdditionalInfo">Additional Info</label>
            <div class="col-sm-9">
                <textarea id="AdditionalInfo" rows="5" name="AdditionalInfo" maxlength="1000" style="max-width: 100% !important; width: 100%;" class="form-control" placeholder="Big Message">@Model.AdditionalInfo</textarea>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-success" style="width: 100px;" onclick="handleSubmitButton('#updateInstitutionForm', 'InstitutionDatatable')">Save</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
}