src/WebUI/Controllers/BankController.cs
using BLL.Common.Extensions;
using BLL.Common.Interfaces;
using BLL.Common.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    [Authorize(Roles = "Operator Bancar")]
    public class BankController : Controller
    {
        private readonly IBankRepository _bankRepository;
        private readonly IDocumentRepository _documentRepository;
        public BankController(IBankRepository bankRepository, IDocumentRepository documentRepository)
        {
            _bankRepository = bankRepository;
            _documentRepository = documentRepository;
        }

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<ActionResult> GetServiceDocuments()
        {
            try
            {

                var resultService = await _bankRepository.GetAllSerciceThree(User.GetUserId());
                return PartialView("~/Views/Bank/_ServiceReports.cshtml", resultService);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }

        [HttpGet]
        public async Task<ActionResult> GetSLADocuments()
        {
            try
            {

                var resultSLA = await _bankRepository.GetAllSLAThree(User.GetUserId());
                return PartialView("~/Views/Bank/_SLAReports.cshtml", resultSLA);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }
        [HttpGet]
        public async Task<ActionResult> GetProjects()
        {
            try
            {

                var resultProjects = await _bankRepository.GetAllProjectThree(User.GetUserId());
                return PartialView("~/Views/Bank/_Projects.cshtml", resultProjects);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }

        [HttpGet]
        public async Task<ActionResult> GetDetails(int id)
        {
            try
            {

                var document = await _documentRepository.GetDocument(id);
                return PartialView("~/Views/Bank/_Info.cshtml", document);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }

        [HttpGet]
        public async Task<ActionResult> DownloadDocumentById(int id)
        {
            try
            {
                var result = await _bankRepository.GetFileById(id);

                if (result != null && System.IO.File.Exists(result.Path))
                {
                    var streamResponse = new FileStream(result.Path, FileMode.Open, FileAccess.Read);

                    return File(streamResponse, "application/octet-stream", result.Name);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }


    }
}

src/WebUI/Controllers/UserController.cs
using BLL.Common.Interfaces;
using BLL.UserDTOs;
using BLL.TableParameters;
using BLL.Validator;
using FluentValidation;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : BaseController
    {
        private readonly IUserRepository _userRepository;
        private readonly IInstitutionRepository _institutionRepository;
        private readonly IValidator<CreateUserDto> _CreateUserDtoValidator;
        private readonly IValidator<UpdateUserDto> _UpdateUserDtoValidator;
        public UserController(IUserRepository userRepository, IInstitutionRepository institutionRepository,
            IValidator<CreateUserDto> CreateUserDtoValidator,
            IValidator<UpdateUserDto> updateUserDtoValidator)
        {
            _userRepository = userRepository;
            _institutionRepository = institutionRepository;
            _CreateUserDtoValidator = CreateUserDtoValidator;
            _UpdateUserDtoValidator = updateUserDtoValidator;
        }


        public ActionResult Index() => View();


        [HttpPost]
        public async Task<ActionResult> LoadUserDatatable(DataTablesParameters parameters)
        {
            try
            {
                var result = await _userRepository.GetAllUsers(parameters);
                return Json(new
                {
                    draw = parameters.Draw,
                    recordsFiltered = parameters.TotalCount,
                    recordsTotal = parameters.TotalCount,
                    data = result
                });

            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetDetails(int id)
        {
            try
            {

                var user = await _userRepository.GetUser(id);

                return PartialView("~/Views/User/Details.cshtml", user);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }

        private async Task PrepareUserRoles(UpdateUserDto userDto)
        {
            var rolesVm = await _userRepository.GetRolesAsync();
            var selectListItemRoleVm = rolesVm.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name,
                Selected = userDto != null ? userDto.RolesId.Contains(x.Id) : false
            });

            ViewBag.Roles = selectListItemRoleVm;

            if(userDto != null)
            {
                await PrepareUserInstitution(userDto.Id);
            }
            
            //if (userDto.RolesId.Contains(3) && userDto != null && userDto.IdInstitution != 0 && userDto.IdInstitution != null)
            //{
            //    await PrepareUserInstitution(userDto.Id);
            //}
        }

        [HttpPost]
        public async Task<JsonResult> PrepareUserInstitution(int userid)
        {
            if (userid != 0)
            {
                var userVM = await _userRepository.GetUser(userid);
                var userInstitutionId = userVM.InstitutionId;
                var institutions = await _institutionRepository.GetInstitutions();
                var selectListInstitutionsVm = institutions.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name,
                    Selected = userVM.InstitutionId != 0 ? x.Id == userInstitutionId : false
                });
                ViewBag.Institutions = selectListInstitutionsVm;

                return Json(selectListInstitutionsVm);
            }
            else
            {
                var institutions = await _institutionRepository.GetInstitutions();
                var selectListInstitutionsVm = institutions.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name,
                    Selected = false
                });
                ViewBag.Institutions = selectListInstitutionsVm;
                return Json(selectListInstitutionsVm);
            }
        }
        [HttpGet]
        public async Task<ActionResult> GetCreate()
        {
            try
            {
                //var userVm = await _userRepository.GetUser(id);

                await PrepareUserRoles(null);
                var institutions = await _institutionRepository.GetInstitutions();
                var selectListInstitutionsVm = institutions.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name,
                    Selected = false
                });
                ViewBag.Institutions = selectListInstitutionsVm;
                return PartialView("~/Views/User/Create.cshtml");
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }


        }
        // POST: User/Create
        [HttpPost]
        public async Task<ActionResult> Create(CreateUserDto createUser)
        {
            try
            {
                var validationResult = _CreateUserDtoValidator.Validate(createUser);
                if (!validationResult.IsValid)
                {
                    foreach (var failure in validationResult.Errors)
                    {
                        ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                    }

                    TempData["ErrorUser"] = "ErrorUser";
                    await PrepareUserRoles(null);
                    var institutions = await _institutionRepository.GetInstitutions();
                    var selectListInstitutionsVm = institutions.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                        Selected = false
                    });
                    ViewBag.Institutions = selectListInstitutionsVm;
                    return PartialView("~/Views/User/Create.cshtml", createUser);
                }

                var result = await _userRepository.Add(createUser);
                if (result)
                {
                    // return Json(new { success = true/*, redirectUrl = Url.Action(nameof(Index))*/ });
                    return Json(new { success = true });
                }
                else
                {
                    TempData["ErrorUser"] = "ErrorUser";
                    await PrepareUserRoles(null);
                    var institutions = await _institutionRepository.GetInstitutions();
                    var selectListInstitutionsVm = institutions.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                        Selected = false
                    });
                    ViewBag.Institutions = selectListInstitutionsVm;
                    return PartialView("~/Views/User/Create.cshtml", createUser);
                }

            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }

        [HttpGet]
        public async Task<ActionResult> GetEdit(int id)
        {
            try
            {

                var user = await _userRepository.GetUpdateUser(id);
                await PrepareUserRoles(user);
                return PartialView("~/Views/User/Edit.cshtml", user);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }
        [HttpPost]
        public async Task<ActionResult> Edit(int userId, UpdateUserDto updateUserDto)
        {
            var validationResult = _UpdateUserDtoValidator.Validate(updateUserDto);
            if (!validationResult.IsValid)
            {
                foreach (var failure in validationResult.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }

                TempData["ErrorUser"] = "ErrorUser";
                await PrepareUserRoles(updateUserDto);
                return PartialView("~/Views/User/Edit.cshtml", await _userRepository.GetUpdateUser(userId));
            }
            updateUserDto.Id = userId;
            var result = await _userRepository.Update(updateUserDto);
            if (result)
            {
                // return Json(new { success = true/*, redirectUrl = Url.Action(nameof(Index))*/ });
                return Json(new { success = true });
            }
            else
            {
                TempData["ErrorUser"] = "ErrorUser";
                await PrepareUserRoles(updateUserDto);
                return PartialView("~/Views/User/Edit.cshtml", await _userRepository.GetUpdateUser(userId));
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetDelete(int id)
        {
            try
            {

                var user = await _userRepository.GetUser(id);

                return PartialView("~/Views/User/Delete.cshtml", user);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/_NotFound.cshtml");
            }

        }


        [HttpPost]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var success = await _userRepository.Delete(id);
                if (success)
                {
                    return Json(new { success = true });
                }
                else
                {

src/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/lib/bootstrap-select")
    @Styles.Render("~/lib/jquery-datatables")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("~/Views/Shared/_Modals.cshtml")
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "User", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole("Operator Cedacri"))
                    {
                        <li>@Html.ActionLink("Documents", "Index", "Document", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole("Operator Bancar"))
                    {
                        <li>@Html.ActionLink("Operator Bancar", "Index", "Bank", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                var userName = Context.User.Identity.Name;
                <div class="d-flex">
                    <ul class="navbar-nav">
                        <li>
                            <a class="btn btn-outline-danger" href="@Url.Action("Logout", "Account")">
                                Logout<br /> @userName
                            </a>
                        </li>
                    </ul>
                </div>
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/bootstrap-select")
    @RenderSection("scripts", required: false)
</body>
</html>

src/WebUI/Views/Shared/_Modals.cshtml
<div id="lgModal" class="modal fade bs-example-modal-lg" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="lgModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="LargeModal"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div id="lgModalBody" class="modal-body">

                <div id="errorAlert" class="alert alert-danger" role="alert" hidden>
                    <h5 class="text-danger alert-link"><i class="uil uil-exclamation-octagon text-danger"></i>Error</h5>
                    <span id="errorText" class="text-danger"></span>
                </div>

                <div id="warningAlert" class="alert alert-warning" role="alert" hidden>
                    <h5 class="text-warning alert-link"><i class="uil uil-exclamation-triangle text-warning"></i> Warning</h5>
                    <span id="warningText" class="text-danger"></span>
                </div>

                <div id="spinner-content" class="d-flex justify-content-center">
                    <div class="" name="Growing-Spinners">
                        <div class="spinner-grow text-primary" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <div class="spinner-grow text-secondary" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <div class="spinner-grow text-success" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <div class="spinner-grow text-danger" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <div class="spinner-grow text-warning" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <div class="spinner-grow text-info" role="status" style="height:3rem;width:3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- Begin fullscreen modal -->

<div id="xlModal" class="modal fade bs-example-modal-xl" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="xlModal" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="ExtraLargeModal"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div id="xlModalBody" class="modal-body">

                <div id="errorAlert" class="alert alert-danger" role="alert" hidden>
                    <h5 class="text-danger alert-link"><i class="uil uil-exclamation-octagon text-danger"></i>Error</h5>
                    <span id="errorText" class="text-danger"></span>
                </div>

                <div id="warningAlert" class="alert alert-warning" role="alert" hidden>
                    <h5 class="text-warning alert-link"><i class="uil uil-exclamation-triangle text-warning"></i> Warning</h5>
                    <span id="warningText" class="text-danger"></span>
                </div>

                <div id="spinner-content" class="d-flex justify-content-center">
                    <div class="" name="Growing-Spinners">
                        <div class="spinner-grow text-primary" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                        <div class="spinner-grow text-secondary" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                        <div class="spinner-grow text-success" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                        <div class="spinner-grow text-danger" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                        <div class="spinner-grow text-warning" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                        <div class="spinner-grow text-info" role="status" style="height:3rem;width:3rem;">
                            @* <span class="sr-only">Loading...</span> *@
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--<div id="smModal" class="modal fade bs-example-modal-sm" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="smModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="smModalBody" class="modal-body">
                <div id="spinner-content" class="d-flex justify-content-center">
                    <div class="" name="Growing-Spinners">
                        <div class="spinner-grow text-primary" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                        <div class="spinner-grow text-secondary" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                        <div class="spinner-grow text-success" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                        <div class="spinner-grow text-danger" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                        <div class="spinner-grow text-warning" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                        <div class="spinner-grow text-info" role="status" style="height:3rem;width:3rem;">-->
                            @* <span class="sr-only">Loading...</span> *@
                        <!--</div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>-->